# Generated by Django 4.0.4 on 2023-08-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcenter',
            name='is_disaster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='sa_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
