# Generated by Django 4.0.4 on 2023-09-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0002_healthcenter_is_disaster_healthcenter_sa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcenter',
            name='activity_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
