# Generated by Django 4.0.4 on 2023-09-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppOptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('opt_status', models.CharField(choices=[('opt_in', 'Opt In'), ('opt_out', 'Opt Out')], max_length=7)),
                ('opt_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'index_together': {('username',)},
            },
        ),
    ]
