# Generated by Django 4.0.4 on 2023-09-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_opt_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappopthistory',
            name='source',
            field=models.CharField(choices=[('hera_app', 'Hera App'), ('whatsapp', 'Whatsapp')], default='hera_app', max_length=8),
        ),
    ]
