# Generated by Django 4.0.4 on 2023-09-15 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_health', '0013_alter_pastvaccination_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancy',
            name='declared_number_of_prenatal_visits',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
