# Generated by Django 4.0.4 on 2023-12-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_glossary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='entry_ar',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='entry_en',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='entry_prs',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='entry_pus',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='entry_tr',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
