# Generated by Django 4.0.4 on 2023-06-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_alter_surveytemplate_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytemplatetranslation',
            name='twilio_content_sid',
            field=models.CharField(help_text='Whatsapp Template SID in Twilio Content editor', max_length=255, null=True),
        ),
    ]
