# Generated by Django 4.0.4 on 2023-06-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_notificationtemplatevariable_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='twilio_content_sid',
            field=models.CharField(help_text='Whatsapp Template SID in Twilio Content editor', max_length=255, null=True),
        ),
    ]
